import "./meanValue.js";
import "./reversedSequence.js";
import "./quarterOfTheYear.js";
import "./sentenceSmash.js";
import "./removingElements.js";
import "./makeUpperCase.js";
import "./convertAStringToANumber.js";
import "./stringRepeat.js";
import "./maximumAndMinimumValues.js";
import "./reduceButGrow.js";
import "./checkForFactor.js";
import "./switchItUp.js";
import "./findTheFirst .js";
import "./keepUpTheHoop.js";
import "./howGoodAreYouReally.js";
import "./countingSheep.js";
